-------------------------------------
Суффикс	    Основная ответственность
-------------------------------------
Factory	    создать готовый объект
Builder	    постепенно построить объект
Loader	    загрузить из источника
Saver	    сохранить
Downloader	получить извне (API, HTTP, SDK)
Repository	предоставить доступ к данным независимо от хранения
Cache	    кешировать
Parser	    разобрать внешний формат
Mapper	    преобразовать одну модель в другую
Validator	проверить корректность
Converter	преобразовать представление без изменения смысла
Resolver	найти/разрешить зависимость или объект
Provider	предоставить ресурс или данные без управления ими
Service	    предоставить предметные операции
Manager	    управлять жизненным циклом, состоянием или группой объектов
       	    управляет подсистемой сервисов билдеров лоадеров...
            или просто фасад класс над этими системами
Preparer    подготавливает объект
Initializer инициализирует объект
Hydrator    наполняет объект
Ensurer     гарантирует наличие данных в объекте


-------------------------------------
Pattern     Основная ответственность
-------------------------------------
Factory
Builder
Facade
Adapter
Decorator
Strategy
Observer
